spring:
  application:
    name: hissenet
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

mail:
  from:
    email: ${MAIL_FROM:noreply@hissenet.com}
    name: ${MAIL_FROM_NAME:HisseNet Aracı Kurum}
  verification:
    code-length: 6
    expiry-minutes: 10
  templates:
    enabled: true